[package]
name = "openrgb-shader-controller"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.29.1"
rand = "0.8.5"
regex = "1.11.1"
reqwest = { version = "0.12.9", features = ["blocking"] }
serde_json = "1.0.133"
undo = "0.51.0"
